SNOWFLAKE_TO_DUCKDB_MAPPING = {
    "TYPE": "type",
    "RECORD_DELIMITER": 'new_line',
    "FIELD_DELIMITER": "delimiter",
    "FILE_EXTENSION": "file_extension",
    "SKIP_HEADER": "skip",
    "PARSE_HEADER": "header",
    "DATE_FORMAT": "dateformat",
    "TIME_FORMAT": None,
    "TIMESTAMP_FORMAT": "timestampformat",
    "BINARY_FORMAT": None,
    "ESCAPE": "escape",
    "ESCAPE_UNENCLOSED_FIELD": None,
    "TRIM_SPACE": "trim_space",
    "FIELD_OPTIONALLY_ENCLOSED_BY": "quote",
    "NULL_IF": "nullstr",
    "COMPRESSION": "compression",
    "ERROR_ON_COLUMN_COUNT_MISMATCH": "null_padding",
    "VALIDATE_UTF8": None,
    "SKIP_BLANK_LINES": None,
    "REPLACE_INVALID_CHARACTERS": None,
    "EMPTY_FIELD_AS_NULL": None,
    "SKIP_BYTE_ORDER_MARK": "skip_byte_order_mark",
    "ENCODING": None
}
