name: Deploy to AWS Lambda

on:
  push:
    branches: [ main ]

jobs:

  build:

    name: Build Image and Deploy
    runs-on: ubuntu-latest
    environment: deploy
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry-type: public
      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: public.ecr.aws/m5p8n9s4/universql
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY:$IMAGE_TAG -f snowflake.aws.lambda.Dockerfile --push .
      - uses: int128/deploy-lambda-action@v1
        with:
          function-name: universql-server
          image-uri: public.ecr.aws/m5p8n9s4/universql:latest
          #image-uri: 730335382627.dkr.ecr.us-east-1.amazonaws.com/universql:latest