name: deploy
on: [push]
jobs:
  version:
    name: "Check Snowflake CLI version"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - uses: Snowflake-Labs/snowflake-cli-action@v1.5
        with:
          cli-version: "latest"
      - name: Test project
        env:
          SNOWFLAKE_CONNECTIONS_BASE64: ${{ secrets.SNOWFLAKE_CONNECTIONS_BASE64 }}
        run: |
          export SNOWFLAKE_CONNECTIONS=$(printf '%s' "$SNOWFLAKE_CONNECTIONS_BASE64" | base64 -d | tr '\r' '\n')
          snow --version
          snow connection test --environment ci-aws-us-east-1
          python run_benchmark.py /resources/dwh-benchmark/clickbench.sql > /resources/dwh-benchmark/results.json
      - uses: actions/upload-artifact@v4
        with:
          name: icebergbench
          path: /resources/dwh-benchmark